### ISSUE TITLE
creeping

### ISSUE THREAD

**Issue by redispade** [temporasanguinis/MUD#199]
uno sciame di insetti inghiotte Rosetta la receptionist!  
uno sciame di insetti trasforma Rosetta la receptionist in un cumulo di ossa sanguinanti.  
Il tuo sangue si raggela non appena senti il grido di morte di Rosetta la receptionist!

[Issue created by federicozanardi: 2019-07-25]

**Comment by Nesland** [comment]
Sono state tolte le locazioni limitrofe che portavano in rece all'aperto che permettevano il creep.
