### ISSUE TITLE
[Bug] Armi holdabili

### ISSUE THREAD

**Issue by redispade** [temporasanguinis/MUD#232]
**Bug:**

Le armi che hanno come posizione indossabile sia _Impugnato_ che _Tenuto_ obbligano a rimuovere sia hold che scudo per poter essere holdate.

**Testato con:**

* PG senza dual wield
* PG con dual wield
* Armi con peso 1 \(_coltello d'allenamento_ in donation\)

‌

[Issue created by Ashur-Mattia: 2019-09-14]
[Last updated on bitbucket: 2020-05-10]

[Comment created by stefano_de_biasi: 2020-05-10]
Confermato bug nel caso l'arma, anche a peso 1, se ha sia hold che wield, non permette l'uso dello scudo

[Comment created by Trattore: 2020-02-14]
anche con str 18

[Comment created by redispade: 2020-02-14]
quanta forza ha il pg ?

**Comment by Nesland** [comment]
le armi che hanno sia Impugnato che holdato sono considerate ingrombanti a prescindere quindi funziona correttamente.
