### ISSUE TITLE
bug mon sum e gruppi

### ISSUE THREAD

**Issue by redispade** [temporasanguinis/MUD#292]
ricordavo il problema e ho fatto un test

in pratica se sono da solo ed evoco dei monsum, quindi li gruppo

se qualcuno fa gw, compare “Il tuo gruppo e' stato rimosso perche' e' troppo piccolo.”

non dovrebbe

[Issue created by federicozanardi: 2019-11-21]
[Last updated on bitbucket: 2020-05-01]

[Comment created by Trattore: 2020-05-01]
Confermo il problema, molto fastidioso tra l’altro da Druido che vive di monsum.

In pratica evochi i monsum, lo gruppi, e viene creato il gruppo.

nei tick successivi appena un qualsiasi giocatore fa gwho, compare scritto “Il tuo gruppo e' stato rimosso perche' e' troppo piccolo.” e vieni tolto dal gruppo.

devi rigruppare tutti i monsum e rifare il gruppo da capo sperando che nessuno nel frattmepo faccia gwho.

Esiste il modo di risolvere la cosa ?

**Comment by Nesland** [comment]
risolto in fix passati
