### ISSUE TITLE
chiave serponi

### ISSUE THREAD

**Issue by redispade** [temporasanguinis/MUD#391]
la chiave poppa nella parte basse \(statuetta serpente\)

la porta e' nella parte alta

la bassa poppa \+ lentamente delll’alta, il che rende facile non poter accedere al tempio

sarebbe meglio avere i tempi repop allineati o magar far poppare la stastuetta nell’alta direttamente

[Issue created by federicozanardi: 2020-07-23]

**Comment by Nesland** [comment]
repop sincronizzati
