### ISSUE TITLE
fix steal enchantment che va oltre AMS

### ISSUE THREAD

**Issue by msimic** [temporasanguinis/MUD#4]
i mob maghi non odvrebbero poter fare steal enchantment se il pg ha ams

Scritta: X pronuncia le parole 'La tua magia e' in mio possesso

**Comment by Nesland** [comment]
testato sul tester con alucard in AMS dal cavaliere nero. 
crash al secondo round dopo lo stab.

**Comment by msimic** [comment]
Non so se steala il DK,
ma ha procedure speciali di dispel e altro.

Potresti verificare su mob maghi senza procedure speciali.
Se funziona dopo abbastanza casi senza crash allora c'e' un bug sul DK da
fixxare.

**Comment by msimic** [comment]
E se succede cosi' serve creare un task per il DK.

**Comment by Nesland** [comment]
![Image](https://user-images.githubusercontent.com/20583740/188202071-60db0562-7080-41bf-93ca-688af96a4383.png)

risolto

**Comment by msimic** [comment]
questo non e' steal ma dispel
riapro :D

**Comment by Nesland** [comment]
![Image](https://user-images.githubusercontent.com/20583740/188202498-fd4b56df-8fec-47cc-ab94-74e085099abc.png)

era questo lo screen :P

**Comment by Nesland** [comment]
testato con margonita
