### ISSUE TITLE
Chiave Demoni

### ISSUE THREAD

**Issue by redispade** [temporasanguinis/MUD#408]
Nella Zona dei demoni tempo fa fu apportato un cambiamento alle chiavi che ad oggi impedisce ai giocatori di poter raggiungere la stanza del tesoro del vescovo.

In pratica il muro di mattoni richiede la chiave grigia \(in possesso del wight\) per essere aperto,

mentre il vescovo ha il ciondolo del forziere dove c’e l’elmo dell’eterna visione.

Il problema sorge dal momento che la chiave grigia del wight, scompare dopo l’uso  e viene usata per aprire la cattedrale, mentre il muso da aprire con la medesima chiave si trova dentro la cattedrale stessa quindi con 1 chiave che trovi fuori la cattedrale, apri sia la cattedrale , sia un muro dentro di essa, solo che la chiave scompare dopo essere stata usata una volta.

Questo rende impossibile arrivare a quella stanza a meno di intervento divino per ottenere un duplicato della chiave oppure all’apertura del muro stesso.

‌

Soluzione proposta , o alzare a 2 il numero di usi della chiave grigia, o cambiare la chiave necessaria \(magari spostandola sul ciondolo del vescovo\)

![](https://bitbucket.org/repo/Krzx6MM/images/963297516-image.png)
‌

[Issue created by Trattore: 2021-09-18]

[Comment created by marsovac: 2021-09-18]
fixxato io

[Comment created by paoloterre: 2021-09-18]
Si potrebbero usare due chiavi diverse, si.

**Comment by Nesland** [comment]
risolto, la parete si apre senza chiave, lo scrigno richiede il ciondolo del vescovo
