### ISSUE TITLE
Remap Zones con corretto type

### ISSUE THREAD

**Issue by Nesland** [temporasanguinis/MUD#415]
Ripassare le Mappe Zmud per assegnare il corretto zone tpye per parsarle poi nel webclient

**Comment by Nesland** [comment]
![Image](https://user-images.githubusercontent.com/20583740/188308792-10b40d24-ee17-4c61-b9a0-5c959fe09356.png)

**Comment by Nesland** [comment]
Le Zone barrate sono quelle gia parsate e corrette, verra editato di volta in volta solo questo commento

- ~~La citta' di Midia~~
- ~~HAON-DOR-LIGHT~~
- ~~Le antiche terre greche~~
- ~~Morrowindl Ingresso (by Gabriel)~~
- ~~Daemion's manor~~
- ~~Stabh's forgotten realms~~
- ~~Castel Destino (by Dryden)~~
- ~~La Scacchiera~~
- ~~L'arena di Felix (Trad. by Kiruna)~~
- ~~Il laboratorio alchemico di Blackmouth (Trad. by Tyrant)~~
- ~~La montagna titanica (by Dryden)~~
- ~~Il villaggio gitano (Trad. by Rayden)~~
- ~~La citta' di New Thalos (Trad. by Gambit)~~
- ~~La fortezza di Kaneloon~~
- ~~Incantevole Foresta by Yeden~~
- ~~Iperborea by AlAzif~~
- ~~Arctica (Trad. by Tyrant)~~
- ~~Krall's ancient sleeping forest~~
- ~~Le Fogne di Midia~~
- ~~L'abisso dei demoni (Trad. by Rayden)~~
- La fortezza dei giganti del fuoco
- ~~Gilda Dei Demoni~~
- Spiderhaunt di Celestian (trad. by Ash)
- Darkenwood (Trad. by Tyrant)
- Il regno di Aryador (by Aryhann)
- ~~Il fiume di Midia~~
- ~~La citta' abbandonata di Orshingal (Trad. by Tyrant)~~
- ~~Mordilnia~~
- ~~L'isola del destino di Vilian (Trad. by Martinus)~~
- ~~I Cavalieri del Destino~~
- ~~La parte sud di Midia~~
- Le Terre Meridionali
- Le terre oscure di Lyth (Trad. by Gothic)
- Le miniere di Falrhun (Trad. by Kiruna)
- Castel Mistamere (Trad. by Draman)
- ~~Gilda degli Eroi~~
- ~~La nuova contea~~
- La giungla del culto del serpente
- ~~Il tempio oscuro (by Logan)~~
- ~~Alberone~~
- La foresta di Rhowyn
- Il castello di Camelot (by Dryden)
- I possedimenti del Barone Etnegar
- Il grande deserto dell'est
- ~~Asgard~~
- La torre delle viverne (Trad. by Rayden)
- ~~Le estensioni del Tempio di Midia~~
- I Campi d'Addestramento
- L'Arena
- ~~Gilda dei Gladiatori~~
- Drowcity (by Alexander e Rayden)
- Il tempio dei Ninja (by Dryden)
- ~~Gilda Casato di Loth~~
- La Via Per Avalon
- Il villaggio dei mezzogiganti (by Dryden)
- ~~Il cimitero di Midia (Trad. by Rurik)~~
- ~~Cavalierato di Solamnia~~
- ~~Piano astrale~~
- ~~Rayden's Castle Black Heart~~
- Ingresso e Castello di Tricksty
- ~~I crepacci dei giganti dei ghiacci (by Tyrant)~~
- ~~Gilda delle Amazzoni~~
- Ingresso Valle dei Maghi
- L'Avamposto di Giove
- La vecchia citta' di Thalos
- ~~L'Hoeur (Trad. by Nalith)~~
- La valle maledetta (by Tyrant)
- ~~Il tempio del dio dimenticato (by Dryden)~~
- La piramide maledetta di Akin-Ra (Trad. by Tyrant)
- L'Alta Torre della Magia (Trad. by Daemion)
- Sauria (Trad. by Tyrant)
- ~~Confraternita di midia~~
- La Valle di Myrran by Fulgore
- La tenuta nera (by Fulgore)
- L'avamposto degli Orchi(Fortezza invasa)
- La torre di tortura degli alieni (Trad. by Tyrant)
- ~~Gilda Dark~~
- ~~Ravenloft (by Martinus & Tyrant)~~
- ~~La terra dei quickling~~
- ~~La terra capovolta (Trad. by Tyrant)~~
- Wonderland
- ~~La Foresta degli elfi (Trad. by Martinus)~~
- ~~Medness~~
- ~~Gilda dei Pazzi~~
- La fortezza dei giganti delle colline
- Il castello maledetto di Adamant
- Le Terre del Grande Lag
- La cittadella delle nuvole (by Radagast)
- Nightingale's Geldor
- ~~Il Palazzo degli Skexie~~
- Rhyiana (Trad. by Tyrant)
- ~~Fortezza Astrale~~
- ~~La roccaforte dei giganti dei ghiacci (by Tyrant)~~
- ~~Nightingale's Utopya~~
- ~~Atlantide, The Lost World (by Mordor)~~
- ~~I Sotterranei dei Campi~~
- ~~I quartieri alti di Midia (by Nalith)~~
- ~~HAON-DOR-DARK~~
- ~~Il vulcano White Plume~~
- ~~Le montagne orientali~~
- Il sentiero nella valle (Trad. by Auriel)
- Il sentiero tra le colline (Trad by Auriel)
- ~~Caverne Sotterranee (Trad. by Rayden)~~
- Il regno dei nani di Gilimdor (Trad. by Nalith)
- Le montagne di Myrran
- ~~la Foresta Misteriosa (trad by Gambit)~~
- ~~Ade (tradotta da Gothic)~~
- ~~il Monte Olimpo~~
- ~~Il liv. inf. delle fogne~~
- ~~Le gallerie del sottomondo (Trad. by Tyrant)~~
- ~~Labirinto Fogne~~
- La foresta di Sommerlund (by Tyrant)
- Il Regno di Diebs (by Fulgore)
- L'antro degli esperimenti (by Tyrant)
- Il tempio degli elementi
- Le terre infestate di Arachnos (Trad. by Tyrant)
- La foresta di Mirkwood (Trad. by Nalith)
- Dryden's Evil Church
- ~~Il tempio dei Druidi Banditi (Trad. by Tyrant)~~
- Le caverne dei trogloditi (Trad. by Nalith)
- ~~Il Tribunale di Midia~~
- ~~Il Monastero dei Monaci~~
- ~~Gilda dei Mercenari~~
- ~~Il boschetto~~
- ~~Sotto la Scacchiera~~
- Piramide dei serpenti - parte alta
- La piramide dei serpenti - parte bassa
- ~~L'avamposto abbandonato di Rhyodin (Trad. by Stellos, Kiruna & Nalith)~~
- ~~Cavalieri dello Zodiaco (by Tornado)~~
- ~~Le cave di Castel Destino (by Dryden)~~
- ~~Moria livelli 3-4~~
- ~~Le Terre Libere di Uhmea~~
- ~~La Scuola-MUD di TS~~
- L'isola di Deadhame (Trad. by Tyrant)
- Il labirinto sopra le nuvole (by Martinus)
- ~~Brea e Gran Burrone (by Tornado)~~
- ~~La torre di Isengard (by Ashur e Auriel)~~
- ~~Corno Tozzo~~
- ~~Il mercato rionale~~
- La foresta nascosta di Wildedhil (by Fulgore)
- ~~Giungla by Irash~~
- ~~Il Villaggio dei Brownie (by Phentol, Kandlash, Yasmin, Kendall)~~
- La citta' di Salus (by WaiLer)
- Le terre meridionali e il villaggio di Toewin (by Nalith)
- ~~La Carrozza~~
- Monte Rotto
- ~~La Metropolitana (by Ash)~~
- Midraash
- ~~Il labirinto del tempio di Midia (Trad. by Kash)~~
- ~~Il bosco dei druidi di Namor (Trad. by Stellos)~~
- La terra incantata di Naiti (by Nis)
- La Via Lattea (by Phentol, Kandlash, Yasmin, Kendall)
- I portali dimensionali (By Fulgore)
- Gli abissi di Kaltenland (by Tyrant)
- ~~La citta di Menzoberrazan (by Tyrant)~~
- ~~l palazzo delle nebbie eterne di Agarhal (by Nalith)~~
- La citta' costiera di Rhila (by Nalith)
- ~~La gabbia dei combattimenti di Gan'har (by Auriel & Nalith)~~
- Mordor's Dark Land (by Samak, Dimitri, Auriel)
- Tamriel, l'isola di Summerset (by Auriel)
- ~~~Tamriel, Cyrodiil (by Auriel)~~
- Tamriel, Skyrim (by Auriel)
- La Tomba di Lilith
- ~~La baia grande di Targis (By Nalith)~~
- ~~La citta' di Midia ad Halloween (by Phoenix)~~
- ~~La Necropoli di Midia (by Phoenix)~~
- ~~La citta' di Comp (by Nalith)~~
- ~~Le prigioni di Orfaler (by Nalith)~~
- La faglia di Worden (by Nalith)
- ~~Le caverne dimenticate di Kaligrin (by Nalith)~~
- ~~Le caverne dimenticate di Kaligrin (by Nalith)~~
- ~~I luoghi segreti (by Nalith)~~
- ~~La citta' di Lankar~~
- L'acquitrino di Irselt (by Nalith & Guybrush)
- ~~Il museo di Tempora Sanguinis (by Tyrant)~~

**Comment by msimic** [comment]
ho messo la repo TS2Client-contrib

Sposta li la issue perche questo non ha a che fare con il mud stesso plz

**Comment by Nesland** [comment]
spostata in ts2 client-contrib
