### ISSUE TITLE
HELP: listino, aggiungere che per scrigni sacche e teche personali il costo flag ACCOUNT e' gratis

### ISSUE THREAD

**Issue by Nesland** [temporasanguinis/MUD#421]
fatto, e committato

**Comment by msimic** [comment]
riapro:
nuova regola: per questi oggetti sara gratuito il flag
e dalla prossima versione avranno il flag preimpostato quando droppano

**Comment by Nesland** [comment]
Nesland committed b35e406
just now

Modificato Listino secondo issue MUD #421
