### ISSUE TITLE
daily quest: usa incantesimo da bacchetta, bastone o pergamena

### ISSUE THREAD

**Issue by msimic** [temporasanguinis/MUD#7]

**Comment by msimic** [comment]
serve una lista di incantesimi da mettere a random

**Comment by Nesland** [comment]
Bacchetta scheggiata  per prot elementali
Pergamene di shield room a orshingal (poesie)
bastone di astral (aryann)
bastone eartquake (elminster)
pergamena dispel (trixsty)
pergamena remove curse (trickysty/mercenari)
bacchetta drain (torre magia)
bastone nero marrone (shield a gruppo stabh)
bachetta verde e celeste (ice storm a krall)
pergamena di monsum (sia orshingal sia altrove)

**Comment by msimic** [comment]
ok togliendi il remove curse che si compra il alcune gilde andrebbe bene
ancora un paio andrebbe bene cmq

**Comment by msimic** [comment]
sarebbe anche buono mettere qualche spell minore che si trova in vari posti poco frequentati giusto pe rincentivare esplorazione

**Comment by Nesland** [comment]
direi magic missile (asta cadavere mordor e altrove)
pergamena know monster (mazzo carte wonderland)
